/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function LogoModel(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gltf/Logo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[840.97, 623.94, 605.5]}
        rotation={[1.36, -0.31, -0.04]}
        scale={[2.18, 2.18, 2.18]}
      >
        <group position={[8.78, -1172.3, -10.43]}>
          <mesh
            geometry={nodes.Lathe_5.geometry}
            material={nodes.Lathe_5.material}
            position={[-3.79, 6.25, -222.31]}
            scale={[1.5, 2.5, 1.5]}
          />
          <mesh
            geometry={nodes.Lathe_4.geometry}
            material={nodes.Lathe_4.material}
            position={[-3.79, 6.25, 222.31]}
            scale={[1.5, 2.5, 1.5]}
          />
          <mesh
            geometry={nodes.Lathe_3.geometry}
            material={nodes.Lathe_3.material}
            position={[-224.55, 6.25, 3.85]}
            scale={[1.5, 2.5, 1.5]}
          />
          <mesh
            geometry={nodes.Lathe_2.geometry}
            material={nodes.Lathe_2.material}
            position={[224.55, 6.25, 3.85]}
            scale={[1.5, 2.5, 1.5]}
          />
          <mesh
            geometry={nodes.Lathe.geometry}
            material={nodes.Lathe.material}
            position={[-3.79, 6.25, 3.85]}
            scale={[1.5, 2.5, 1.5]}
          />
        </group>
        <group position={[5, -982.62, -6.58]} rotation={[0, 0, 0]}>
          <mesh
            geometry={nodes.Cone_1.geometry}
            material={nodes.Cone_1.material}
            position={[1.01, 114.81, -3.52]}
          />
          <mesh
            geometry={nodes.Shape_4.geometry}
            material={nodes.Shape_4.material}
            position={[10.43, 76.5, -238.82]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Shape_3.geometry}
            material={nodes.Shape_3.material}
            position={[-5.02, 76.5, 238.82]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Shape_2.geometry}
            material={nodes.Shape_2.material}
            position={[-253.09, 76.5, -10.45]}
          />
          <mesh
            geometry={nodes.Shape.geometry}
            material={nodes.Shape.material}
            position={[253.09, 76.5, -10.45]}
          />
        </group>
        <mesh
          geometry={nodes.Text_7.geometry}
          material={nodes.Text_7.material}
          position={[159.02, -841.59, -175.68]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          geometry={nodes.Text_6.geometry}
          material={nodes.Text_6.material}
          position={[-150.65, -850.46, 149.91]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          geometry={nodes.Text_5.geometry}
          material={nodes.Text_5.material}
          position={[-1.15, 74.15, -233.94]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          geometry={nodes.Text_4.geometry}
          material={nodes.Text_4.material}
          position={[-215.75, 65.04, -5.03]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Text_3.geometry}
          material={nodes.Text_3.material}
          position={[230.77, 86.15, -5.74]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
          position={[7.51, 83.2, 212.88]}
        />
        <mesh
          geometry={nodes.Top.geometry}
          material={nodes.Top.material}
          position={[8.79, 1806.01, -8.08]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.ConeTop.geometry}
          material={nodes.ConeTop.material}
          position={[8.18, 1676.76, -9.55]}
          rotation={[0, 0, 0]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.CylinderTopMiddle.geometry}
          material={nodes.CylinderTopMiddle.material}
          position={[8.18, 1587.86, -9.55]}
          rotation={[0, 0, 0]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.cloneTopTop.geometry}
          material={nodes.cloneTopTop.material}
          position={[7.92, 1585.04, -8.08]}
        />
        <mesh
          geometry={nodes.cloneTopMiddle.geometry}
          material={nodes.cloneTopMiddle.material}
          position={[7.92, 1213.18, -6.03]}
        />
        <mesh
          geometry={nodes.cloneTopBottom.geometry}
          material={nodes.cloneTopBottom.material}
          position={[8.31, 979.14, -8.18]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.rightCloneBody.geometry}
          material={nodes.rightCloneBody.material}
          position={[7.51, 0.73, -6.58]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.leftCloneBody.geometry}
          material={nodes.leftCloneBody.material}
          position={[7.51, 0.73, -6.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.cloneBottom.geometry}
          material={nodes.cloneBottom.material}
          position={[7.51, -568.26, -6.58]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Body.geometry}
          material={nodes.Body.material}
          position={[6.51, -295.02, -9.53]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.Cone_3.geometry}
          material={nodes.Cone_3.material}
          position={[8.18, 1508.78, -9.55]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={nodes.Cylinder_3.material}
          position={[8.18, 1391, -9.55]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.Cone_2.geometry}
          material={nodes.Cone_2.material}
          position={[8.18, 1200.49, -9.55]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={nodes.Cylinder_2.material}
          position={[8.18, 871.78, -9.55]}
          scale={[3.18, 3.18, 3.18]}
        />
        <mesh
          geometry={nodes.Cone.geometry}
          material={nodes.Cone.material}
          position={[6.51, 649.59, -9.53]}
          rotation={[0, -0.37, 0]}
          scale={[3.18, 3.18, 3.18]}
        />
      </group>
      <group position={[809, 426.5, -102.37]} scale={[2.53, 2.53, 2.53]}>
        <mesh
          geometry={nodes.Torus_12.geometry}
          material={nodes.Torus_12.material}
          position={[0, 0, -384.55]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_10.geometry}
          material={nodes.Torus_10.material}
          position={[0, 0, -251.6]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_8.geometry}
          material={nodes.Torus_8.material}
          position={[0, 0, -88.78]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_7.geometry}
          material={nodes.Torus_7.material}
          position={[0, 0, 66.5]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_6.geometry}
          material={nodes.Torus_6.material}
          position={[0, 0, 171.3]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_5.geometry}
          material={nodes.Torus_5.material}
          position={[0, 0, 125.74]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus_2.geometry}
          material={nodes.Torus_2.material}
          position={[0, 0, 14.6]}
          rotation={[0, 0, 0]}
          scale={[1, 1, 1]}
        />
        <mesh
          geometry={nodes.Torus.geometry}
          material={nodes.Torus.material}
          position={[0, 0, -295.85]}
          rotation={[0, 0, 0]}
          scale={[1, 1, 1]}
        />
      </group>
      <pointLight
        intensity={2.7}
        decay={2}
        distance={10000}
        color="#606060"
        position={[-609.22, -957.26, 3578.29]}
      />
      {/* <OrthographicCamera
        makeDefault={false}
        far={50135}
        near={-5385}
        position={[210.49, 364.36, 1149.51]}
        rotation={[0.32, -0.34, 0.11]}
      /> */}
      <directionalLight
        intensity={2.8}
        decay={2}
        color="#ececec"
        position={[0, 1, 8042.21]}
        rotation={[0, 0, 0]}
      />
      <OrthographicCamera
        makeDefault={false}
        far={50000}
        near={-50000}
        position={[24.89, -41.03, 942.61]}
        rotation={[0.28, -0.35, 0.1]}
      >
        <directionalLight
          intensity={0.9}
          decay={2}
          color="#000000"
          position={[850000, 1300000, 1000000]}
          rotation={[-0.92, 0.48, -0.34]}
        />
      </OrthographicCamera>
      <mesh
        geometry={nodes.Torus_copy.geometry}
        material={nodes.Torus_copy.material}
        position={[825.19, 426.92, -1357.34]}
      />
      {/* <mesh
        geometry={nodes.Sphere_copy.geometry}
        material={nodes.Sphere_copy.material}
        position={[809, 426.5, -2047.54]}
        scale={[2.53, 2.53, 2.53]}
      /> */}
    </group>
  )
}

useGLTF.preload('/gltf/Logo.gltf')
