export const colors = [
  'var(--orange-20)',
  'var(--orange-30)',
  'var(--orange-40)',
  'var(--orange-40)',
  'var(--orange-50)',
  'var(--blue-20)',
  'var(--blue-30)',
  'var(--blue-40)',
  'var(--blue-50)',
  'var(--purple-20)',
  'var(--purple-30)',
  'var(--purple-40)',
  'var(--purple-50)',
]
